id: P52A224E6
initial_creation_type: input
source_metadata:
  title: Ngawang Kunga Lodrö
  parent: 2. Collected works
  source: https://sakyalibrary.com
  bases:
    0ad0:
      title: བླ་ཆེན་འཕགས་པའི་དངུལ་གདུང་རིན་པོ་ཆེའི་དཀར་ཆག་དགེ་ལེགས་བཅུད་ཀྱི་ཉིང་ཁུ་མྱོང་གྲོལ་ཆེན་མོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 0ad0.txt
      order: 1
    1a72:
      title: ཇོ་བོ་རིན་པོ་ཆེ་འོད་ཟེར་འགྱེད་མ་འབྱོན་ཁུངས།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 1a72.txt
      order: 2
    cff5:
      title: བཞི་ཐོག་མགོན་ཁང་ཆེན་མོ་གསར་དུ་བཞེངས་པའི་དཀར་ཆག་བླ་མའི་ལུང་བསྟན་མངོན་དུ་གྱུར་པའི་ངོ་མཚར་གཏམ་གྱི་ཕྲེང་བ་ཞེས་བྱ་བ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: cff5.txt
      order: 3
    f02c:
      title: དཔལ་ལྡན་ས་སྐྱ་དང་ངོར་ཨེ་ཝཾ་ཆོས་ལྡན་གཉིས་ཀྱི་རིང་ལུགས་འཛིན་པ་རྣམས་ཀྱིས་ཐོག་དྲངས་ས་ལུགས་ཡོངས་རྫོགས་ཀྱི་བསྟན་པའི་སྦྱིན་བདག་སྡེ་དགེ་ཆོས་རྒྱལ་རིན་ཆེན་གྱི་ཐུགས་དམ་དད་རྟེན་ཐང་སྐུ་ཆེ་ཆུང་བཅུ་བདུན་གྱི་དཀར་ཆག་ངོ་མཚར་རྒྱ་མཚོའི་བང་མཛོད།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: f02c.txt
      order: 4
    1da5:
      title: ཆོས་གྲྭ་ཆེན་པོ་གསང་སྔགས་བདེ་ཆེན་གླིང་གི་བཅའ་ཡིག་ལྷག་བསམ་ཉི་འོད་གསལ་བའི་འོད་སྣང་།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 1da5.txt
      order: 5
    607c:
      title: ཆོས་གྲྭ་ཆེན་པོ་ཐུབ་བསྟན་ལྷ་ཁང་ཆེན་མོའི་བཅའ་ཡིག་ངོ་མཚར་ཉིང་ཁུ་ཉེས་སེལ་ལེགས་སྤེལ་གྱི་སྨན་འཆི་བ་མེད་པའི་བདུད་རྩི།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 607c.txt
      order: 6
    42c2:
      title: གདན་ས་ཆེན་པོའི་བྱ་བ་ལས་ཀྱི་སྣེ་མོར་མངགས་པ་རྣམས་ཀྱི་བཅའ་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 42c2.txt
      order: 7
    ae1e:
      title: རྩེ་ཐབ་པ་རྣམས་ནས་བྱ་དགོས་ཀྱི་རྣམ་གཞག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: ae1e.txt
      order: 8
    789a:
      title: ལྷ་ཁང་ཆེན་མོའི་དགེ་འདུན་གཡོས་ཁང་གི་ལས་བྱེད་རྣམ་གཞག་གསལ་སྟོན་གྱི་ཡི་གེ་ལས་འབྲས་གསལ་བའི་མེ་ལོང་།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 789a.txt
      order: 9
    d14a:
      title: ཆོས་གྲྭ་ལྷོ་བྱང་ཐུན་མོང་གི་རུང་ཁང་པ་རྣམས་ནས་བྱ་དགོས་རྣམ་གཞག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: d14a.txt
      order: 10
    f406:
      title: བར་ཐབ་པ་རྣམས་ནས་བྱ་དགོས་རྣམ་གཞག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: f406.txt
      order: 11
    43bd:
      title: དམངས་ཐབ་པ་རྣམས་ཀྱིས་བྱ་བ་བྱེད་ཚུལ་གྱི་རྣམ་གཞག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 43bd.txt
      order: 12
    b28c:
      title: མགོ་ཟླའི་བཀའ་འགྱུར་བཅའ་ཚོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: b28c.txt
      order: 13
    9cc3:
      title: དཔལ་རྩེ་གདོང་ཆོས་སྡེ་གསང་ཆེན་སྨྲ་བའི་གླིང་གི་བཅའ་ཡིག་བསླབ་བྱའི་གནང་བཀག་གསལ་བར་སྟོན་པ་ས་སྟེང་པདྨོ་རྒྱས་པའི་ཉི་འོད་ཕྲིན་ལས་མཁའ་ཁྱབ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 9cc3.txt
      order: 14
    46b3:
      title: བསམ་ཡས་ལྕོག་གྲྭའི་བཅའ་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 46b3.txt
      order: 15
    a66e:
      title: ཆོས་གྲྭ་ཆེན་པོ་ཆོས་འཁོར་ལྷུན་པོའི་བཅའ་ཡིག་རིན་པོ་ཆེ་ཟུང་གི་ཞབས་འདེགས་བསླབ་བྱའི་གནང་བཀག་གསལ་བར་སྟོན་པའི་བཅའ་ཡིག་རྣམ་དག་ཆོས་ཁྲིམས་གསལ་བའི་ཉིན་བྱེད།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: a66e.txt
      order: 16
    877e:
      title: རྒྱུན་སྒྲོག་བཞི་གྲྭའི་བཅའ་ཚེ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 877e.txt
      order: 17
    3e09:
      title: ཧོར་རྩ་བོད་རྩར་སོང་བའི་སྤྱི་འགྲོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 3e09.txt
      order: 18
    98a2:
      title: ཤྲཱི་ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས་སངས་རྒྱས་བསྟན་པའི་རྒྱལ་མཚན་དཔལ་བཟང་པོའི་ཡི་གེ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 98a2.txt
      order: 19
    6a97:
      title: གླང་ནག་བཀྲ་ཤིས་ཆོས་སྡིངས་དགེ་འདུན་རྣམས་ལ་གནང་བའི་སྤྱི་འགྲོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 6a97.txt
      order: 20
    dd39:
      title: དབུ་མཛད་བྱམས་པ་བསྟན་འཛིན་བར་སྡིངས་རྫོང་ཆུང་ལ་ཕེབས་སྐབས་ཀྱི་སྤྱི་འགྲོའི་ཁྲ་གཞི།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: dd39.txt
      order: 21
    e89c:
      title: ཤེས་དཀར་རྫོང་དཔོན་དགའ་བོ་པོར་གནང་བའི་སྤྲིང་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: e89c.txt
      order: 22
    c029:
      title: བར་སྡིངས་རྫོང་ཆུང་དཔོན་སློབ་བྱམས་པར་གནང་བའི་སྤྱི་འགྲོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: c029.txt
      order: 23
    9b6e:
      title: ཆུ་ཡོས་ཟླ་བ་༤ཚེས་༡༠ལ་གནང་བའི་ཁྲ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 9b6e.txt
      order: 24
    1dc9:
      title: སྒ་འདྲའི་གཞི་བདག་ལ་སྤྲིང་ཡིག་དང་། དེའི་ཀ་ལ་ལྷོ་མར་སྦྱར་བ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 1dc9.txt
      order: 25
    1c32:
      title: ཧོར་ཁང་གསར་བར་གནང་བའི་སྤྲིང་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 1c32.txt
      order: 26
    1d40:
      title: དཔལ་ས་སྐྱའི་གཞི་བདག་ཁྱད་པར་ཅན་ཀླུ་རྒྱལ་གཙུག་ན་རིན་ཆེན་འཁོར་དང་བཅས་པ་ལ་སྤྲིངས་པ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 1d40.txt
      order: 27
    816f:
      title: སྔགས་འཆང་ཆེན་པོ་ནས་བཟུང་གདུང་བརྒྱུད་རིམ་ཅན་གྱི་རི་རྒྱ་ཀླུང་རྒྱ་ལ་ཐུགས་གལ་ཤིན་ཏུ་ཆེ་བར་མཛད་པ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 816f.txt
      order: 28
    450d:
      title: རྣམ་རབ་ཀློང་རྩ་ལྷོ་པས་ཞུས་པའི་སྤྲིང་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 450d.txt
      order: 29
    6e29:
      title: དཔོན་ཚེ་དབང་རྣམ་རྒྱལ་པ་ལ་གནང་བའི་ཐང་ཀའི་རྒྱབ་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 6e29.txt
      order: 30
    8d93:
      title: ཁའུ་སྨན་ཆབས་ཀྱི་གཞི་བདག་སྤྱི་ལ་སྤྲིང་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 8d93.txt
      order: 31
    a793:
      title: རྗེ་བཙུན་ས་སྐྱ་པའི་སྐྱབས་འོག་རྣམས་ཀྱི་གནོད་བྱེད་ལ་སྤྲིངས་པ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: a793.txt
      order: 32
    0d17:
      title: འཛམ་གླིང་བྱང་ཕྱོགས་ཀྱི་ཐུབ་པའི་རྒྱལ་ཚབ་དཔལ་ལྡན་ས་སྐྱ་པའི་གདུང་རབས་རིན་པོ་ཆེའི་བྲིས་ཐང་བཞེངས་ཚུལ་ངོ་མཚར་རྒྱ་མཚོའི་གཏེར།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 0d17.txt
      order: 33
    26e1:
      title: ངོར་ཆེན་རྡོ་རྗེ་འཆང་གི་ལམ་འབྲས་བཀའ་རྒྱ་ཐིམ་པའི་གཟིགས་སྣང་འབྲི་ཐོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 26e1.txt
      order: 34
    da5d:
      title: སྒྲུབ་ཐབས་རྒྱ་མཚོའི་ཞལ་ཐང་བྲིས་ཐོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: da5d.txt
      order: 35
    b7f3:
      title: ཡབ་རྗེ་བླ་མཆོད་ཞལ་ཐང་འབྲི་ཐོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: b7f3.txt
      order: 36
    c3d9:
      title: ཤིང་ཕག་ཟླ་ཚེས་ལ་ཡབ་རྗེ་དམ་པའི་མཆོད་ཐང་རྒྱབ་གཟུངས་འབྲི་ཐོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: c3d9.txt
      order: 37
    fde4:
      title: ཐར་རྩེ་རྡོ་རྗེ་འཆང་གི་སྐུ་པུར་ལ་སྙན་ཤལ་ཕུལ་བའི་ཞལ་དབྱངས།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: fde4.txt
      order: 38
    74ed:
      title: མཁའ་སྤྱོད་བེའུ་བུམ་བཞེངས་བྱང་།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 74ed.txt
      order: 39
    f4b6:
      title: རྣམ་སྲས་སྐུ་བཞེངས་ཚུལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: f4b6.txt
      order: 40
    eea5:
      title: གོས་སྐུ་ཞལ་འབྱེད་སྐབས་ཀྱི་ཐོ་ཆུང་།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: eea5.txt
      order: 41
    f3e3:
      title: ལྷ་ཆེན་མཁན་གསར་སྐོས་སྐབས་ཕུན་སུམ་ཚོགས་པའི་བཀྲ་ཤིས་ཀྱི་ཐོ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: f3e3.txt
      order: 42
    0e33:
      title: འཇམ་འདོན་བྱ་ཚུལ་མ་རིག་མུན་སེལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 0e33.txt
      order: 43
    1af7:
      title: གཡའ་ལུང་འཇག་གཤོངས་ཀྱི་འཁོན་སྐུ་འབུམ་བྱིན་ཅན་ལ་ཉམས་གསོ་བགྱིས་སྐབས་གཟུངས་འཕར་སོང་ཐོ་བཀོད་པ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 1af7.txt
      order: 44
    7c7c:
      title: རྣམ་འཕྱང་ཆུ་སྟོད་ས་པཎ་འཁྲུངས་ཚེས་ཐོག་གསེར་ཁྲིར་སྐྱབས་མགོན་གདུང་མཆོག་ནས་རྣམ་འགྲེལ་གཞུང་སྐྱོར་མཛད་སྐབས་འཕན་འབུལ་བའི་ཞལ་བྱང་།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 7c7c.txt
      order: 45
    3c41:
      title: རྒྱན་མཆོག་དུས་མཆོད་དཔྱད་ཁྲ་མཁན་རིན་པོ་ཆེའི་དབུས་ཕུན་སུམ་ཚོགས་པའི་དགེ་འདུན་རྣམས་ལ་ཞུ་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 3c41.txt
      order: 46
    718b:
      title: རྒྱལ་བའི་བཀའ་འགྱུར་སྒྲོགས་པའི་དགེ་འདུན་རྣམས་ལ་སྙན་དུ་གསོལ་བ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 718b.txt
      order: 47
    80dc:
      title: དགེ་འདུན་པ་རྣམས་ལ་སྐྱབས་འཇུག་ཞུ་ཡིག
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 80dc.txt
      order: 48
    173e:
      title: ཡོས་ལོ་སྣྲོན་ཟླའི་ཉེར་གཅིག་ནས་ཚེས་མཆོད་ཆེན་མོ་སོགས།དེ་རྣམས་ཀྱི་ཆོས་སྤྱོད་གཏོང་དེབ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 173e.txt
      order: 49
    edec:
      title: རྒྱལ་སྲས་ཀུན་གྱི་འཇུག་ངོགས་ཐེག་ཆེན་སྤྱི་བྱེ་བྲག་ལ་འཇུག་ཚུལ་ཟབ་དོན་སྒྲོན་མེ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: edec.txt
      order: 50
    f361:
      title: རྒྱལ་དབང་རིན་པོ་ཆེར་ཞབས་བརྟན་ཞལ་བཞེས།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: f361.txt
      order: 51
    ab3e:
      title: ཕྱོགས་བཅུ་དུས་གསུམ་སོགས་ཀྱི་རྗེས་སུ་ཞེས་པར།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: ab3e.txt
      order: 52
    a380:
      title: རྩེ་གདོང་རིན་སྒང་སྤྱི་བོར་གནང་བ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: a380.txt
      order: 53
    bb19:
      title: ཡུམ་སྐལ་བཟང་བདེ་སྐྱིད་བུ་འཁྲིད་མའི་དགོངས་རྫོགས་ཀུན་གྱི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: bb19.txt
      order: 54
    0e6e:
      title: འབུམ་ཐང་དངུལ་གདུང་རིན་པོ་ཆེའི་གདན་རབས་བླ་བརྒྱུད་བཅས་གསར་བཞེངས་སྐབས་སྦྱིན་བདག་སྐུའི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 0e6e.txt
      order: 55
    83c2:
      title: ཐར་རྩེ་རྡོ་རྗེ་འཆང་གི་སྨན་སྐུའི་ནང་བཞུགས་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 83c2.txt
      order: 56
    a4dd:
      title: བསམ་གླིང་སྨོན་བདེ་བའི་འཕེལ་ཆེན་གྱི་ཆེད་དུ་གནང་བའི་འདོད་གསོལ་བཀའ་རྩོམ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: a4dd.txt
      order: 57
    e1eb:
      title: བདུད་འདུལ་མཆོད་རྟེན་ཉམས་གསོ་སྐབས་ཀྱི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: e1eb.txt
      order: 58
    d118:
      title: སྦུས་སྐྱེད་རྟེན་གྱི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: d118.txt
      order: 59
    5fa7:
      title: བཀའ་བློན་ཐོན་པའི་ངོར་གནང་བ་དང་མདའ་དཔོན་ཕུ་ལུང་པའི་ངོར་མཛད།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 5fa7.txt
      order: 60
    e085:
      title: ཡེར་པར་བཞུགས་པའི་ཀླུ་དབང་སྐུའི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: e085.txt
      order: 61
    501c:
      title: འོན་རྒོད་དུ་སོང་བའི་སྐུ་རྣམས་ཀྱི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 501c.txt
      order: 62
    c95c:
      title: འཕགས་སྡེ་སློབ་དཔོན་ནས་ཞུས་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: c95c.txt
      order: 63
    e200:
      title: པད་ཚལ་གྱིས་ཞུས་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: e200.txt
      order: 64
    43e8:
      title: གཟིམ་འོད་རྗེས་སྒྲུབ་འཇམ་དབྱངས་ཀྱི་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 43e8.txt
      order: 65
    907d:
      title: བཅོལ་ལྡན་འདས་དེ་བཞིན་གཤེགས་པ་དགྲ་བཅོམ་པ་ཡང་དག་པར་རྫོགས་པའི་སངས་རྒྱས་རིགས་པ་དང་ཞབས་སུ་ལྡན་པ་ཞེས་པ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 907d.txt
      order: 66
    dd71:
      title: སྐུ་གསུང་ཐུགས་རྟེན་གྱི་གཟུངས་གཞུག་འདོད་གསོལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: dd71.txt
      order: 67
    4d4b:
      title: རྟེན་ཐམས་ཅད་ཀྱི་གནས་གསུམ་དུ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 4d4b.txt
      order: 68
    ec4b:
      title: རྒྱལ་བའི་ལོ་དཔལ་ས་སྐྱའི་ལྷ་ཁང་ཆེན་མོའི་ཁྱམས་སྟོད་གསེར་ཁྲིར་ཞལ་དྲོའི་སྐབས་ཀྱི་ཤིས་བརྗོད་དང་དགེ་འདུན་ལ་སྙན་སྒྲོན་ཡི་གེ་ངོ་མཚར་སྣང་གསལ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: ec4b.txt
      order: 69
    6fde:
      title: དཔལ་ས་སྐྱའི་ཆོས་སྲིད་ལ་དགེ་ལེགས་འབྱུང་བའི་སྒོ་ཤིས་བརྗོད་ཕུན་ཚོགས་གཙུག་རྒྱན།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 6fde.txt
      order: 70
    b166:
      title: འདི་ནང་གི་ཚིགས་བཅད་འདི་མཁན་ཆེན་ཞི་བ་འཚོའི་གཙུག་ཏོར་དྲི་མེད་ཚ་ཆོག་ནས་འབྱུང་།རྒྱ་སྐད་དང་བི་ཝརྟ་ཞལ་དཀར་ཆོས་རྗེ་ངག་དབང་ཤེས་རབ་ཀྱིས་མཛད་ཅིང་།ཞལ་དྲོ་ལྷ་ཁང་དགེ་ལེགས་རྒྱ་མཚོའི་འབྱུང་གནས་ཞེས་ས་སྐྱ་པ་ཀུན་བློས་བཏགས།མུ་ཁོ་ཥྨ་དེ་ཝ་གྲྀ་ཧ་ཤྲེ་ཡ་ས་མུ་དྲཱ་ནཾ་ཀཱ་རཱ་ཏྲ་ཤུ་བྷ།།ཞལ་དྲོ་ལྷ་ཁང་དགེ་ལེགས་རྒྱ་མཚོའི་འབྱུང་གནས་འདི་ན་དགེ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: b166.txt
      order: 71
    9ad3:
      title: གནས་གསར་བ་ངག་དབང་ཀུན་དགའ་ལེགས་པའི་འབྱུང་གནས་ཀྱི་རྣམ་ཐར་ངོ་མཚར་རབ་འབྱམས།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 9ad3.txt
      order: 72
    211c:
      title: རིགས་བརྒྱའི་ཅོད་པན་ས་སྐྱ་པ་ཆེན་པོ་སྔགས་འཆང་ངག་དབང་ཀུན་དགའ་བསོད་ནམས་གྲགས་པ་རྒྱལ་མཚན་དཔལ་བཟང་པོའི་རྣམ་པར་ཐར་པ་ལས་དགུང་གི་བགྲང་གཞི་ལྔ་བཅུ་ཚུན་གྱི་མ་ཚང་བ་ཁ་སྐོང་བ་ལེགས་བྱས་ཀྱི་རྒྱ་མཚོ་སྤེལ་བར་བྱེད་པ་དད་པའི་ཆུ་རྒྱུན་ཤཱཀྱའི་བཙུན་པ་ཀུན་དགའ་བློ་གྲོས་ཀྱིས་མཛད་པ།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 211c.txt
      order: 73
    007f:
      title: དཔལ་ས་སྐྱ་པ་ཆེན་པོ་ཀུན་དགའ་བློ་གྲོས་ཀྱི་རྣམ་ཐར་ངོ་མཚར་འཕྲུལ་གྱི་རོལ་རྩེད་སྡེ་བཞིའི་འབྱུང་གནས་ཀུན་དགའ་བཀྲ་ཤིས་ཀྱིས་མཛད་པ་བཅས་བཞུགས་སོ།།
      author: ས་སྐྱ་པ་ངག་དབང་ཀུན་དགའ་བློ་གྲོས།
      base_file: 007f.txt
      order: 74
created_at: '2022-04-06T16:47:24.897477'
last_modified_at: '2022-04-06T16:47:24.897487'
